id = "luaux"
name = "LuauX"
version = "0.1.0"
schema_version = 1
authors = ["morikyt"]
description = "LuauX — Full Luau language support for Zed with Roblox snippets."
repository = "https://github.com/MorikTV/LuauX"
license = "MIT"

[grammars.luau]
repository = "https://github.com/4teapo/tree-sitter-luau"
rev = "1d25ccb7b2afb85fc0523c4bca3331ad52c55106"
